fixtures:
    responseContentNeedJsonEncode: true
    GET_244f453d18b2308fd4fac6b7900fa4a6:
        request:
            url: /api/content/article/90494
            method: GET
            content: null
        response:
            status: 200
            content:
                id: 90494
                title: 'Baliance Devol double la mise'
                type: brief
                contentType: null
                slug: baliance-devol-double-la-mise-90494
                teaser: null
                isPublished: true
                dateCreate: { date: '2015-02-25 17:32:19', timezone_type: 3, timezone: Europe/Paris }
                dateUpdate: { date: '2015-02-26 15:38:41', timezone_type: 3, timezone: Europe/Paris }
                datePublish: { date: '2015-02-26 08:32:33', timezone_type: 3, timezone: Europe/Paris }
                dateExpire: null
                filename: null
                content: "<div id=\"U101170557188sa\">\r\n<div>\r\n<div><u><em>Enghien, Prix de Chennevi&egrave;res</em></u> - D&eacute;j&agrave; laur&eacute;ate le 15 janvier dernier, <strong>Baliance Devol</strong> a enlev&eacute; sa deuxi&egrave;me course de l&#39;hiver ce mercredi &agrave; Enghien. &ldquo;<em>C&#39;est une pouliche qui met du temps &agrave; se mettre en route</em> indique Yves Dreux &agrave; son retour aux balances. J<em>e suis parti en l&eacute;ger retrait, puis nous avons eu la bonne course apr&egrave;s. Tout s&#39;est bien pass&eacute; et elle a trac&eacute; une tr&egrave;s belle ligne droite. Elle devrait d&eacute;sormais avoir un peu de repos et sera revue avec int&eacute;r&ecirc;t l&#39;hiver prochain</em>&rdquo;. Si la laur&eacute;ate laisse une belle impression, <strong>Black Rain</strong>, termine elle aussi de tr&egrave;s belle mani&egrave;re, apr&egrave;s avoir progress&eacute; dans le sillage de la repr&eacute;sentante d&#39;Yves Dreux. <strong>Bea de Beauval </strong>qui a eu un bon parcours &agrave; la corde s&#39;empare de la troisi&egrave;me place.</div>\r\n</div>\r\n</div>"
                isHotNews: true
                image: null
                commentaire: null
                raceDate: { date: '2015-02-25 00:00:00', timezone_type: 3, timezone: Europe/Paris }
                raceMeeting: 1
                raceNumber: 5
                raceDiscipline: 1
                author: { id: 18, nom: Paris-Turf.com, slug: paris-turf-com }
                isForSale: false
                legend: null
                keywords: 'Baliance Devol,Prix de Chennevières'
