fixtures:
    get_urltest:
        request:
            url: "urltest"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content"
    get_urltest2:
        request:
            url: "urltest2"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 2"
    get_urltest3:
        request:
            url: "urltest3"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 3"
    get_urltest4:
        request:
            url: "urltest4"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 4"
    get_urltest5:
        request:
            url: "urltest5"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 5"
    get_urltest6:
        request:
            url: "urltest6"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 6"
    get_urltest7:
        request:
            url: "urltest7"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 7"
    get_urltest8:
        request:
            url: "urltest8"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 8"
    get_urltest9:
        request:
            url: "urltest9"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 9"
    get_urltest10:
        request:
            url: "urltest10"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 10"