fixtures:
    get_urltest:
        responseContentNeedJsonEncode: true
        request:
            url: "urltestget"
            method: "GET"
            content:
        response:
          status: "200"
          content:
            LastName: "Dummy"
            Firstname: "Dummyer"

    post_urltest:
        request:
            url: "urltest"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content"
    post_urltest2:
        request:
            url: "urltest2"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 2"
    post_urltest3:
        request:
            url: "urltest3"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 3"
    post_urltest4:
        request:
            url: "urltest4"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 4"
    post_urltest5:
        request:
            url: "urltest5"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 5"
    post_urltest6:
        request:
            url: "urltest6"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 6"
    post_urltest7:
        request:
            url: "urltest7"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 7"
    post_urltest8:
        request:
            url: "urltest8"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 8"
    post_urltest9:
        request:
            url: "urltest9"
            method: "POST"
            content: "test"
        response:
          status: "200"
          content: "response content 9"
    post_urltest10:
        request:
            url: "urltest10"
            method: "POST"
            content: "test"
        response:
          status: "400"
          content: "response content 10"