imports:
    - { resource: repositories.yml }
    - { resource: commands.yml }
    - { resource: queries.yml }
    - { resource: specification.yml }

parameters:
    virhi_lazy_mock_api.domain.service.read.class: Virhi\LazyMockApiBundle\Mock\Domain\Service\Mock\ReadService
    virhi_lazy_mock_api.domain.service.write.class: Virhi\LazyMockApiBundle\Mock\Domain\Service\Mock\WriteService

services:
    virhi_lazy_mock_api.domain.service.read:
        class: %virhi_lazy_mock_api.domain.service.read.class%
        arguments:
            - @virhi_lazy_mock_api.infrastructure.repository.redis.finder
            - @virhi_lazy_mock_api.infrastructure.repository.redis.list_finder
            - @virhi_lazy_mock_api.infrastructure.repository.redis.mock

    virhi_lazy_mock_api.domain.service.write:
        class: %virhi_lazy_mock_api.domain.service.write.class%
        arguments:
            - @virhi_lazy_mock_api.infrastructure.repository.redis.attacher
            - @virhi_lazy_mock_api.infrastructure.repository.redis.remover
