parameters:
#    virhi_lazy_mock_api.example.class: Virhi\LazyMockApiBundle\Example

services:
#    virhi_lazy_mock_api.example:
#        class: %virhi_lazy_mock_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
